# Generated by Django 2.2 on 2019-10-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(choices=[('당뇨병', '당뇨병'), ('유방암', '유방암'), ('위암', '위암'), ('우울증', '우울증'), ('호스피스 완화의료', '호스피스 완화의료'), ('치매', '치매')], max_length=190, unique=True)),
                ('disease_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=190)),
                ('keyword_description', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disease_keyword', to='dipex.Disease')),
            ],
            options={
                'unique_together': {('disease', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('e_mail', models.CharField(max_length=190, unique=True)),
                ('phone_number', models.CharField(max_length=190, unique=True)),
                ('mobile_phone_number', models.CharField(max_length=190, unique=True)),
                ('organization', models.CharField(blank=True, max_length=190)),
                ('major', models.CharField(blank=True, max_length=190)),
                ('is_expert', models.BooleanField(default=False)),
                ('research_field', models.CharField(blank=True, max_length=190)),
                ('expert_bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
                ('video_path', models.FileField(blank=True, max_length=190, unique=True, upload_to='video_original')),
                ('video_path_encrypt', models.FileField(blank=True, max_length=190, upload_to='video_encrypt')),
                ('subtitle', models.TextField()),
                ('interviewee_age', models.IntegerField(default=0)),
                ('diagnosis_age', models.IntegerField(default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disease_interview', to='dipex.Disease')),
                ('keyword', models.ManyToManyField(to='dipex.DiseaseKeyword')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dipex.Person')),
            ],
        ),
    ]
